### ISSUE TITLE
Make the token available

### ISSUE THREAD

**Issue by maxbakke** [MitjaBezensek/SharpBucket#111]
Is there a way to access the access token?
I am attempting to run clone commands  and need to pass along the token.

Thanks!

**Comment by mnivet** [comment]
We have that but in current release it's only internal, not publicly exposed
see here: https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucket/Authentication/OAuth2TokenProvider.cs

and we have a git clone usage in our unit tests.
See the usage of the token provider here:
https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucketTests/GitHelpers/OAuth2GitCredentialsProvider.cs
And our git clone operation done with LibGit2Sharp in the constructor of that class:
https://github.com/MitjaBezensek/SharpBucket/blob/master/SharpBucketTests/GitHelpers/TestRepositoryBuilder.cs

I suppose we can easily expose to public the `OAuth2TokenProvider` if it match your needs
But for the `OAuth2GitCredentialsProvider` I won't be so simple. It depends on a git implementation (*LibGit2Sharp*) on which we don't want to take any dependency for the package we provide, and which may not be the one that you expect to use.
So Maybe we can though to provide a second package that provide that class. Or you can simply copy/past it in your own code, since creating a package for so little may not be relevant.

Take a look at those classes and tell me if just exposing the `OAuth2TokenProvider` to public would be good for you.

**Comment by mnivet** [comment]
OAuth2TokenProvider has been improved and will be exposed to public in the next release
