### ISSUE TITLE
PullRequest activity endpoints missing approval data

### ISSUE THREAD

**Issue by p-kostic** [MitjaBezensek/SharpBucket#116]
The following endpoints currently have activity information, containing updates (and comments?). However, I am missing a separate data type for the approval of a pullrequest (and by whom). 

* /repositories/{username}/{repo_slug}/pullrequests/activity `GET`
   * Implemented by: `PullRequestsResource.GetPullRequestLog()`
   * Tested: yes

* /repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/activity `GET`
   * Implemented by: `PullRequestResource.GetPullRequestActivity()`
   * Tested: yes

This functionality is listed in the BB documentation, and I have indeed seen it using curl, but I cannot retrieve it within C#. 

(https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/activity)

Am I missing something or could this be added?

**Comment by mnivet** [comment]
The unit tests of the `PullRequestResource` seems to demonstrate that indeed, you can retrieve the comments and updates on a pullrequest through the `GetPullRequestActivity()` method, but there is nothing about approvals.
And the BitBucket documentation is pretty short when it comes to detail the entity returned by the activity endpoint...

So I've start to write new unit test and I've been able to catch some json responses that include approvals. I will complete our `Activity` entity so that you can access to that data in C#.

**Comment by p-kostic** [comment]
Thank you so much for the quick reply and integrating it that quick too!

**Comment by mnivet** [comment]
It's now available in V0.12.0
