### ISSUE TITLE
How to list the tags my repository?

### ISSUE THREAD

**Issue by y-eshua** [MitjaBezensek/SharpBucket#117]
How to list my tags with Sharp Bitbucket?

**Comment by mnivet** [comment]
You should do something like that:
```CSharp
var sharpBucket = new SharpBucketV2();
sharpBucket.OAuth2ClientCredentials("consumerKey", "consumerSecret");
var tags = sharpBucket.RepositoriesEndPoint()
                      .TagResource("accountName", "repoSlugOrName")
                      .ListTags();
```

But since that method is not yet covered by our unit tests (see [here](https://github.com/MitjaBezensek/SharpBucket/blob/master/Coverage.md#tag-resource)), there is a small probability that it doesn't work any more. So let me know if you encounter an issue with that.

**Comment by y-eshua** [comment]
Thankss!
