### ISSUE TITLE
Make paginated data iterable via generators

### ISSUE THREAD

**Issue by 0x1mason** [MitjaBezensek/SharpBucket#12]
I realized belatedly that I probably should have used `yield` and returned `IEnumerable<T>` instead of `List<T>` in PR #10 . By using generators, we only make as many HTTP calls as are required for the user's purpose regardless of whether or not they know `max` ahead of time.

I'd like to either refactor the ListX functions to return `IEnumerable<X>` or at least add `IterateX` functions.  I could do this very quickly. The result would be something like this:
```csharp
        public List<Repository> ListRepositories(string accountName, int max = 0){
            var overrideUrl = _baseUrl + accountName + "/";
            return GetPaginatedValues<Repository>(overrideUrl, max);
        }

        public IEnumerable<Repository> IterateRepositories (string accountName) {
            var overrideUrl = _baseUrl + accountName + "/";
            foreach (var val in IteratePaginatedValues<Repository>(overrideUrl )) {
                yield return val;
            }
        }
```

I don't know that we need both versions, tho. Thoughts. @MitjaBezensek?

**Comment by MitjaBezensek** [comment]
I don't think we need both version, it would just make the API confusing. 

I think it's good to be able to set a max on the number of returned items. For example if you would be making a dashboard with latest issues, you might only want to show 10 of them or you might want to show the latest 10 commits,... In uses cases like this it would speed up the calls substantially if you could specify the number of returned items.

I guess you could still count the items with the generator logic and stop iterating when the `max` (if supplied) was reached? I guess the `foreach` loop in the `IterateRepositories` could also be generic, so that we don't repeat it in each `ListX` method?

**Comment by 0x1mason** [comment]
Yeah, you just stop iterating when you hit `max`, it's just up to the user.

I think the fact that I'm having to explain this idea is an indication it's not a good choice for the vanilla API. Maybe I can add some extension methods or something that offer the generator functionality for implementers who want to "opt in".

I cleaned up `GetPaginatedValues<T>` and added a protected generator method (which is used by `GetPaginatedValues<T>`) to make extension easier. Once #10 is merged, I'll submit it for review. You can see the new logic here: https://gist.github.com/0x1mason/250db27ec987534a7efa.

**Comment by MitjaBezensek** [comment]
Nah, I understand the idea. I just think that still having a max parameter is useful so I'd like to keep it. Like you said when you hit the max items just yield break so that it stops iterating.

**Comment by 0x1mason** [comment]
Gotcha +1.
