### ISSUE TITLE
Project Filter on RepositoriesEndPoint

### ISSUE THREAD

**Issue by devheroo** [MitjaBezensek/SharpBucket#121]
what is the best way to get all repos for a certain project ? 
currently , I only see one option that will get all repos from all projects under the Team account .

**Comment by mnivet** [comment]
Maybe you can try to add a filter on the request that list all the projects under the team account ?
The documentation relative to filters is here : https://developer.atlassian.com/bitbucket/api/2/reference/meta/filtering

The project property of the repository resource is not listed as a supported property. But maybe it has been forgotten  ?
So I suggest you to try filter strings like $"project.name=\"{projetcName}\""

otherwise I think you should ask to BitBucket teams directly how to achieve that with their API

**Comment by devheroo** [comment]
Thanks @mnivet , the filter (project.name) you suggested worked.
