### ISSUE TITLE
PostRepository Uses Repository.Name in the POST request URL

### ISSUE THREAD

**Issue by matthewsmith91** [MitjaBezensek/SharpBucket#73]
PostRepository uses the Repository.name property to populate the POST request URL. 

        internal Repository PutRepository(Repository repo, string accountName)
        {
            var overrideUrl = GetRepositoryUrl(accountName, repo.name, null);
            return _sharpBucketV2.Put(repo, overrideUrl);
        }

While the repository name being used in the request URL is required to be lower cased and slugified, it is not a requirement for the repository's name to be lower case or slugified. These should be two separate values.

A simple solution would be to pass _repository from RepositoryResource.cs to RepositoriesEndpoint.PostRepository, similar to how it is done with PutRepository.

        internal Repository PostRepository(Repository repo, string accountName, string repository)
        {
            var overrideUrl = GetRepositoryUrl(accountName, repository, null);
            return _sharpBucketV2.Post(repo, overrideUrl);
        }

**Comment by anh-duc-le** [comment]
The repository json actually has a property called slug.

I use a custom Repository POCO for this.

```
namespace BitbucketPocos
{
    public class Repository
    {
        public Project project { get; set; }
        public string scm { get; set; }
        public bool? has_wiki { get; set; }
        public string description { get; set; }
        public Links links { get; set; }
        public string fork_policy { get; set; }
        public string language { get; set; }
        public string created_on { get; set; }
        public string full_name { get; set; }
        public bool? has_issues { get; set; }
        public Owner owner { get; set; }
        public string updated_on { get; set; }
        public ulong? size { get; set; }
        public bool? is_private { get; set; }
        public string name { get; set; }
        public string uuid { get; set; }
        public string slug { get; set; }
    }
}
```


Meanwhile you could also translate the repository to a slug using the code I used in this PR here: https://github.com/MitjaBezensek/SharpBucket/pull/70/files

**Comment by mnivet** [comment]
When you want to create a new repository (which is the goal of PostRepository) you can't know the UUID, and it's not your duty to guess how names should be transformed to be a valid slug

The pull request #70 done by @anh-duc-le is now re-integrated and do what was needed :
transform the repository name into a slug (code that is called behind the PostRepository method)

So maybe there is still some clean up re-factoring to perform to rename parameter names from `repository` to `repositorySlug` like you suggest @asherber 
But since the fix is re-integrated let's close that issue and I let you open another one if you think that doing some parameter renaming is really necessary

**Comment by asherber** [comment]
Thanks, I'll take a closer look at the code, but it seems to me that the `RepositoryResource` methods could all do with a little cleanup to make their intent cleaner.
