### ISSUE TITLE
Projects API

### ISSUE THREAD

**Issue by iannewson** [MitjaBezensek/SharpBucket#80]
Hi,

I can't see to find any reference to projects in the API. I've looked for the following:

- A way to retrieve a list of projects for a team
- A way to create a new project
- A way to associate a repository with a particular project

Do these APIs exist or am I barking up the wrong tree?

**Comment by mnivet** [comment]
These APIs exist in Bitbucket but they are not yet implemented in SharpBucket

- A way to retrieve a list of projects for a team
  * https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams/%7Busername%7D/projects/
  * Not yet implemented in SharpBucket
- A way to create a new project
  * https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams/%7Busername%7D/projects/#post
  * Not yet Implemented in SharpBucket
- A way to associate a repository with a particular project
  * https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D#put
  * Not yet Implemented in SharpBucket but probably few works to do since the GET, POST and DELETE are implemented

You can have a look here for the current coverage of BitBucket APIs by SharpBucket: https://github.com/MitjaBezensek/SharpBucket/blob/master/Coverage.md

Feel free to help us with a pull request if you need it quickly. Otherwise don't expect that we add support to any of that APIs before end of January.

**Comment by mnivet** [comment]
@iannewson it's now available in V0.9.0 of SharpBucket if you need
